FROM python:3.7-alpine

ENV PYTHONUNBUFFERED 1

RUN apk add --update --no-cache postgresql-client jpeg-dev
RUN apk add --update --no-cache --virtual .tmp-build-deps \
      gcc libc-dev linux-headers postgresql-dev musl-dev zlib zlib-dev

RUN mkdir -p /usr/src/recipes
WORKDIR /usr/src/recipes

COPY ./requirements.txt /usr/src/recipes/requirements.txt
RUN pip install -r requirements.txt

RUN apk del .tmp-build-deps

COPY ./entrypoint.sh /usr/src/recipes/entrypoint.sh
RUN	chmod	+x	/usr/src/recipes/entrypoint.sh

COPY . /usr/src/recipes

RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static
RUN	chmod +x /vol/web


CMD ["/usr/src/recipes/entrypoint.sh"]