# base image
FROM python:3.7.2-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

RUN mkdir -p /usr/src/recipes
WORKDIR /usr/src/recipes

COPY ./requirements.txt /usr/src/recipes/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/recipes/entrypoint.sh
RUN	chmod	+x	/usr/src/recipes/entrypoint.sh

COPY . /usr/src/recipes

# RUN mkdir -p /vol/web/media
# RUN mkdir -p /vol/web/static
# RUN adduser -D user
# RUN chown -R user:user /vol/
# RUN chmod -R 755 /vol/web

CMD ["/usr/src/recipes/entrypoint.sh"]