version: '3.6'

services:

  recipes:
    build:
      context: recipes
      dockerfile: Dockerfile-dev
    volumes:
      - './recipes:/usr/src/recipes'
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@recipes-db:5432/recipes_dev
      - DJANGO_SETTINGS_MODULE=app.settings.development
    depends_on:
      - recipes-db

  recipes-db:
    build:
      context: recipes/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
