# base image
FROM python:3.7.2-slim

# install netcat
RUN apt-get update && \
    apt-get -y install netcat && \
    apt-get clean

RUN mkdir -p /usr/src/recipe-app-api
WORKDIR /usr/src/recipe-app-api

COPY ./requirements.txt /usr/src/recipe-app-api/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/recipe-app-api/entrypoint.sh
RUN	chmod	+x	/usr/src/recipe-app-api/entrypoint.sh

COPY . /usr/src/recipe-app-api

CMD ["/usr/src/recipe-app-api/entrypoint.sh"]